commerce_payment.commerce_payment_gateway.plugin.onsite:
  type: commerce_payment_gateway_configuration
  mapping:
    client_id:
      type: string
      label: 'Client Id'
    client_pass:
      type: string
      label: 'Client Pass'
    simple_kyc:
      type: boolean
      label: 'Simplified KYC'
    tag:
      type: string
      label: 'Tag'
